# Generated by Django 5.0.6 on 2024-06-08 00:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("Department_id", models.AutoField(primary_key=True, serialize=False)),
                ("Department_Name", models.CharField(max_length=25)),
            ],
            options={
                "db_table": "Department",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("Employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("Punch_Card_NO", models.IntegerField(unique=True)),
                ("Name", models.CharField(max_length=25)),
                ("Designation", models.CharField(max_length=30)),
                ("Location", models.CharField(max_length=30)),
                ("DOB", models.DateField()),
                ("DOJ", models.DateField()),
                ("DOL", models.DateField(null=True)),
                ("Parents_Name", models.CharField(max_length=25)),
                ("Martial_Status", models.CharField(max_length=25)),
                ("Permanent_Address", models.TextField()),
                ("Present_Address", models.TextField()),
                ("Blood_Group", models.CharField(max_length=10)),
                ("UAN_Number", models.IntegerField(null=True, unique=True)),
                ("PF_PW", models.IntegerField()),
                ("ESI_Number", models.IntegerField()),
                ("Mobile_No", models.IntegerField()),
                ("Email", models.EmailField(max_length=254, null=True)),
                ("Aadhar_No", models.IntegerField()),
                ("PAN", models.CharField(max_length=25)),
                ("Bank_Acc_NO", models.IntegerField()),
                ("IFSC_Code", models.CharField(max_length=25)),
                ("Bank_Name", models.CharField(max_length=25)),
                ("Emergency_Contact_No", models.IntegerField()),
                ("Contact_No", models.IntegerField()),
                ("Sur_name", models.CharField(max_length=25)),
                ("Qualification", models.CharField(max_length=25)),
                ("Experience", models.CharField(max_length=25)),
                ("Remarks", models.TextField()),
                ("Salary", models.IntegerField()),
                (
                    "Department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.department"
                    ),
                ),
            ],
            options={
                "db_table": "Employee",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("attendance_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.employee"
                    ),
                ),
            ],
            options={
                "db_table": "Attendance",
            },
        ),
        migrations.CreateModel(
            name="Overtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                (
                    "Overtime_hours",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "Overtime_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(59),
                        ],
                    ),
                ),
                (
                    "Employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hub.employee"
                    ),
                ),
            ],
        ),
    ]
